# Generated by Django 5.0.7 on 2024-08-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='dept_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doct_name',
            field=models.CharField(max_length=20),
        ),
    ]
